trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: Docker@2
  displayName: 'Build and Push Docker image'
  inputs:
    command: buildAndPush
    repository: clajke/devopsazurepipeline
    dockerfile: $(Build.SourcesDirectory)/Dockerfile
    containerRegistry: 'Docker Hub'  # Use your Docker Hub service connection name
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Jordan Clarke DevOps(4563fdd1-e2bd-4332-98dc-7facf2d27d5c)'
    azureResourceGroup: 'resource_group_1'
    kubernetesCluster: 'jordaks'
    manifests: 'application-manifest.yaml'